-- 医院诊疗系统（实验3）数据库表结构
-- 兼容 SQLite/MySQL（字段类型以 SQLite 为准，可在 Navicat 中按需调整）

CREATE TABLE IF NOT EXISTS User (
  ID TEXT PRIMARY KEY,
  FULLNAME TEXT,
  USERNAME TEXT UNIQUE,
  PASSWORD TEXT
);

CREATE TABLE IF NOT EXISTS Patient (
  ID TEXT PRIMARY KEY,
  ID_CARD TEXT,
  NAME TEXT,
  SEX INTEGER,
  DOB TEXT,
  HEIGHT REAL,
  WEIGHT REAL,
  MOBILEPHONE TEXT,
  AGE INTEGER,
  CREATEDTIMESTAMP TEXT
);

CREATE TABLE IF NOT EXISTS Department (
  ID TEXT PRIMARY KEY,
  NAME TEXT
);

CREATE TABLE IF NOT EXISTS Doctor (
  ID TEXT PRIMARY KEY,
  EMPLOYEENO TEXT,
  NAME TEXT,
  DEPARTMENT_ID TEXT,
  FOREIGN KEY(DEPARTMENT_ID) REFERENCES Department(ID)
    ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS History (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USER_ID TEXT,
  EVENT TEXT,
  TIMESTAMP TEXT,
  FOREIGN KEY(USER_ID) REFERENCES User(ID)
    ON UPDATE CASCADE ON DELETE SET NULL
);

-- 默认账号：admin / 123456
INSERT OR IGNORE INTO User(ID,FULLNAME,USERNAME,PASSWORD)
VALUES('u-admin','管理员','admin','123456');

